# Setup
title: "The Wiki"
url: https://wiki.phoenixconsoles.org
paginate: 1
baseurl: "/"
permalink: pretty

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - license.md
  - readme.md

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
 ga_analytics: UA-186265977-1

# Specify the author for blog posts
author:
  name: Phoenix Consoles
  url: https://twitter.com/phnxconsoles
  email: wiki@phoenixconsoles.org

# Custom vars
version: 3.0.0

# Navbar page list
nav:
  - title: Blog
    url: /archive

  - title: About
    url: /about
